### ISSUE TITLE
Check merge conflict

### ISSUE THREAD

**Issue by Currerius** [Rapporteket/Rweave#1]
I updated the stent level report to use the new data source (SegmentStent view in staging DB).

Check if the merge conflict after my repo *up still exists and test the report in production.

**Comment by areedv** [comment]
Merge conflict is ok. Corrected two code typos. Now executing without errors. However, it seems like part of the code takes a very long time to run, and I will need to look into it before closing the issue

**Comment by areedv** [comment]
This query:
SELECT
    A.ForlopsID ,
    A.ProsedyreType ,
    SUM(S.ForlopsID>0) AS Nstents ,
    A.ProsedyreDato
FROM
    AngioPCI A
    LEFT JOIN SegmentStent S on A.ForlopsID=S.ForlopsID
GROUP BY ForlopsID;

just takes "forever" to run. Maybe due to lack of indexing?

**Comment by areedv** [comment]
Uh, config is not updated, report does not query staging data...

**Comment by areedv** [comment]
We will have to add staging info to the config. To be done next week. Nowebs then needs to be updated accordingly. Stent rolled back to previous version. Closing this issue, making a new one for what is related to the updated config (staging as data source)
